### ISSUE TITLE
[Suggestion] Chapter/Volume/Special Sorting for Paperback doesn't reflect standard reading experience

### ISSUE THREAD

**Issue by KaitoKid** [ACK72/kavya-paperback#10]
**Describe the bug**

Kavita currently separates media files into either: 
- Volumes
- Specials
- Chapters

We're also making two assumptions:

1.  Most people have sorting set to 'Descending', also known as `Most-Recent`
2. Ongoing media with regular releases do not have volume assignments to each chapter/release at the time of release

Currently, Paperback sorts these with `Specials` at the top, `Volumes` behind them, and `Chapters` w/o volumes at the very bottom, when sorting in descending order.

However, this does not reflect a regular reading experience. I am proposing that it be changed to `Chapters` w/o volumes are at the top as they are assumed to be more recent than those with volumes assignments. 

EDIT: Following Kavita's sorting by `Storyline` would work as well - in fact, that would be the suggested improvement

**Comment by KaitoKid** [comment]
I made some changes to reflect some of the suggestions:

The below changes the sort order
```
const sortHelper = (a, b) => {
	// If volume is 0, consider it greater than any other number
	if (a.volume === 0 && b.volume !== 0) return 1;
	if (a.volume !== 0 && b.volume === 0) return -1;
  
	// If volume is the same, compare chapter numbers and _index
	if (a.volume === b.volume) {
	  return a.chapNum === b.chapNum ? a._index - b._index : a.chapNum - b.chapNum;
	}
  
	// If volume is different, compare volumes
	return a.volume - b.volume;
  };
```

I also suggest removing the `chapter.isSpecial ? j++ ` from how Specials are assigned a chapter number for aesthetics - Specials are typically labeled as `ONESHOT` or `SP02`, which are directly pulled into the title by Kavita at the moment.

**Comment by ACK72** [comment]
Thanks for your suggestion.
I'll check out and try to reflect it soon.

**Comment by ACK72** [comment]
First of all, I apologize for the delay in responding.
I've been thinking a lot about your suggestions, and I'd like to talk about them briefly.

1. I think it would be more intuitive from a file management perspective to have users assign a volume number to a relatively new chapter that hasn't been assigned a volume number. However, I also think your suggestion is reasonable, and adjusted it so that the case where no volume is assigned is higher up than the case where it is assigned.
2. the currently implemented paperback structure only allows the extension to return a numeric chapter number, which makes it impossible to arbitrarily represent a chapter number such as SP01. So, I chose to categorize the specials separately and put them at the top, and this hasn't changed in new version - this takes into account that since they are specials, they will be read after.

I've updated Kavya 1.3.2 with these fixes. If you have any other suggestions or issues, please feel free to file an issue here.
