### ISSUE TITLE
[Feature Request] Change encoding of volume number

### ISSUE THREAD

**Issue by IsXGeo** [ACK72/kavya-paperback#14]
**Describe the bug**
Every chapter of every series since the update to 1.3.5  has Vol -1000000 in its name

**Expected behavior**
For it to not be there

**Screenshots**
![image](https://github.com/ACK72/kavya-paperback/assets/16053230/3be2d90b-82d7-4996-a759-8de0396982fa)

**Comment by Lumilias** [comment]
I'm also getting the same issue, however, I do notice that if I have a volume number defined, it then switches to the chapter being -100000.
![Screenshot 2024-04-14 at 09 54 05](https://github.com/ACK72/kavya-paperback/assets/10852161/df5a3960-245a-4de7-ac2c-4d30a9a0abb8)

Edit: I see what happened now:
`Changed: Loose Leaf volumes are now encoded with the number -100000 instead of 0. This now means users can have a Volume 0 without issue.`
`Encoding: Special (100000), Loose Leaf Volume (-100000).`
From the [Kavita 0.8.0 release notes](https://github.com/Kareadita/Kavita/releases/tag/v0.8.0).

It's not _technically_ a bug. It's a change in how Kavita handles volumes.

**Comment by KaitoKid** [comment]
Updated per #17 , will wait for it to be reviewed & merged in

**Comment by ACK72** [comment]
Thanks for your great work! I have reviewed and merged it to main.
