### ISSUE TITLE
[BUG] Downloaded manga only show the first image as all images,

### ISSUE THREAD

**Issue by meap158** [ACK72/kavya-paperback#2]
Hey it's me again. After you had fixed the issue with the tracker I decided to download a bunch manga and came across another issue. Currently, downloaded manga only show the first image as all images (as in a downloaded manga with 200 pages will show the first image as all 200 pages), while manga that are not downloaded are working fine. 

P/S: While you’re at it, it would be nice if it showed how much storage it will take to download the manga, like the Komga extension. Kavya does show how many pages one chapter has, so it would be perfect if it also had that.

![image](https://user-images.githubusercontent.com/14327094/226183563-f745848b-ccc2-4c92-b738-66da8b591027.png)
![image](https://user-images.githubusercontent.com/14327094/226183569-616b5823-b633-4b89-ad1c-ff9948681d6b.png)

**Comment by meap158** [comment]
All pages are like this:
![Uploading 226184026...]

**Comment by ACK72** [comment]
Thanks for your report. Seems like a bug that has been around for a long time.
Yet, its a paperback related issue, Kavya 1.2.5 has been release with fix of download feature

For displaying file size, unfortunately, it is difficult to implement in kavya.
Since Paperback downloads each single image, it is different from the file size provided by Kavita, which is compressed.

It could be implemented by finding the size of individual single images and merging them all together,
but it will take a "very long time" because the maximum number of requests per second is limited.

**Comment by meap158** [comment]
That’s too bad because I really want to know the file size before downloading. Anyways, it seems like the issue with downloaded manga has been resolved now. Thank you for the speedy update.

**Comment by meap158** [comment]
It’s not working as well as I expected. Now it won’t even start to download and keeps showing this error.

![image](https://user-images.githubusercontent.com/14327094/226199007-858456a1-d0be-4057-be00-f2867db03a9a.png)

**Comment by ACK72** [comment]
Well, its hard to understand what you mean, and figure out the problem.
File an issue within suitable issue templeate, and send log file via email.

**Comment by meap158** [comment]
Sure will do. Where can I send the Paperback log file?

**Comment by ACK72** [comment]
It is in the issue template

**Comment by meap158** [comment]
Thanks. Log file sent.
